# Docker Compose configuration for RASN MCP server
version: '3.8'

services:
  rasn-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rasn-mcp
    command: mcp stdio
    stdin_open: true
    tty: true
    environment:
      - RASN_API_KEY=${RASN_API_KEY:-}
    volumes:
      - ./data:/data:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "rasn", "auth", "status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    labels:
      - "com.rasn.service=mcp"
      - "com.rasn.version=0.1.0"

  # Example: HTTP MCP server (when implemented)
  # rasn-http:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: rasn-http
  #   command: mcp http --port 8080
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - RASN_API_KEY=${RASN_API_KEY:-}
  #   volumes:
  #     - ./data:/data:ro
  #   restart: unless-stopped
  #   healthcheck:
  #     test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3
