[package]
name = "rasn-resolver"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "RASN rasn-resolver crate"

[dependencies]
rasn-core = { path = "../rasn-core" }
